const _regionList = ['Kanto','Johto','Hoenn','Sinnoh','Unova','Kalos','Alola','Galar'];

const _highestAvailableRegion = 6;

const _dungeonList = [
    ["Viridian Forest","Mt. Moon","Diglett's Cave","Rock Tunnel","Rocket Game Corner","Pokémon Tower","Silph Co.","Power Plant","Seafoam Islands","Pokémon Mansion","Mt. Ember Summit","Berry Forest","Victory Road","Cerulean Cave","Ruby Path","Icefall Cave","Sunburst Island","Lost Cave","Pattern Bush","Altering Cave","Tanoby Ruins","Pinkan Mountain"],
    ["Sprout Tower","Ruins of Alph","Union Cave","Slowpoke Well","Ilex Forest","Burned Tower","Tin Tower","Whirl Islands","Mt. Mortar","Team Rocket's Hideout","Radio Tower","Ice Path","Dark Cave","Tohjo Falls","Victory Road Johto","Mt. Silver"],
    ["Petalburg Woods","Rusturf Tunnel","Granite Cave","Fiery Path","Meteor Falls","Mt. Chimney Crater","Jagged Pass","New Mauville","Weather Institute","Mt. Pyre","Magma Hideout","Aqua Hideout","Shoal Cave","Cave of Origin","Seafloor Cavern","Sky Pillar","Sealed Chamber","Victory Road Hoenn"],
    ["Oreburgh Gate","Valley Windworks","Eterna Forest","Old Chateau","Team Galactic Eterna Building","Wayward Cave","Mt. Coronet South","Solaceon Ruins","Iron Island","Lake Valor","Lake Verity","Mt. Coronet North","Lake Acuity","Team Galactic HQ","Spear Pillar","Distortion World","Victory Road Sinnoh","Sendoff Spring","Hall of Origin","Fullmoon Island","Newmoon Island","Flower Paradise","Snowpoint Temple","Stark Mountain"],
    ["Floccesy Ranch","Liberty Garden","Castelia Sewers","Relic Passage","Relic Castle","Lostlorn Forest","Chargestone Cave","Mistralton Cave","Celestial Tower","Reversal Mountain","Seaside Cave","Plasma Frigate","Giant Chasm","Cave of Being","Abundant Shrine","Victory Road Unova","Twist Mountain","Dragonspiral Tower","Moor of Icirrus","Pledge Grove","Pinwheel Forest","Dreamyard","P2 Laboratory"],
    ["Santalune Forest","Connecting Cave","Glittering Cave","Reflection Cave","Kalos Power Plant","Sea Spirit's Den","Poké Ball Factory","Lost Hotel","Frost Cavern","Team Flare Secret HQ","Terminus Cave","Pokémon Village","Victory Road Kalos"],
    ["Trainers' School","Hau'oli Cemetery","Verdant Cavern","Melemele Meadow","Seaward Cave","Ten Carat Hill","Pikachu Valley","Paniola Ranch","Brooklet Hill","Wela Volcano Park","Lush Jungle","Diglett's Tunnel","Memorial Hill","Malie Garden","Hokulani Observatory","Thrifty Megamart","Ula'ula Meadow","Po Town","Aether Foundation","Exeggutor Island Hill","Vast Poni Canyon","Mina's Houseboat","Mount Lanakila","Lake of the Sunne and Moone","Ruins of Conflict","Ruins of Life","Ruins of Abundance","Ruins of Hope","Poni Meadow","Resolution Cave"],
    ["Slumbering Weald Shrine","Galar Mine","Galar Mine No. 2","Rose Tower","Energy Plant","Glimwood Tangle","Dusty Bowl","Warm-Up Tunnel","Courageous Cavern","Brawlers Cave","Tower of Darkness","Tower of Waters","Roaring-Sea Caves","Rock Peak Ruins","Iron Ruins","Iceberg Ruins","Split-Decision Ruins","Lakeside Cave","Dyna Tree Hill","Tunnel to the Top","Crown Shrine"]
];
